### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by ghost** [fastcat/wirelink#18]
Hello, my name is Alfonso Hernandez. I work for the Astian Foundation, a non-profit organization that offers free software and technologies.

We are the organization responsible for development and maintenance of Midori Browser, a popular browser, light, fast, secure and open source.

We are developing a service called K-LamarVPN using WireGuard, which we hope to link with Midori. We would like to establish an alliance with the project to implement it.

What do you think?

**Comment by fastcat** [comment]
Sorry this languished for so long. Not sure if the notification mail went to spam or what.

I'm not sure what you're thinking of from this project. Is the VPN service you're offering a hosted "privacy" service, where the configuration would generally just be a single client connecting to a server? If so, this project is not particularly useful or suitable.

This project is designed for peer-to-peer setups where several client devices want to be able to communicate directly without having to route traffic through a central peer.  For example, I use this to allow multiple laptops of mine to connect to each other directly over the LAN, though still through WireGuard, when both are at a remote location, so that they don't have to funnel traffic out over the WAN and back in.

Also I would stress that this project is _not_ production ready, though it does work for my day-to-day use cases.

That said, I'm open to suggestions & contributions, and you are free to use it under the terms of the AGPL-3.0.

**Comment by fastcat** [comment]
Submitter ghosted
